events {
    worker_connections 1024;
}

http {
    upstream vllm_index {
        server vllm-index-1:8000;
        server vllm-index-2:8000;
    }

    server {
        listen 8000;

        location / {
            proxy_pass http://vllm_index;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            # 禁用缓冲以支持可能的流式输出
            proxy_buffering off;

            # 超时时间加长，因为建索引可能比较慢
            proxy_read_timeout 300s;
            proxy_connect_timeout 300s;
        }
    }
}
