#!/bin/bash
# GitNexus 远程部署脚本 (Bash 版)
# 功能：本地构建 -> 压缩导出 -> SCP 传输 -> 远程加载 -> 容器启动

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${ENV_FILE:-${SCRIPT_DIR}/.env}"
if [ -f "${ENV_FILE}" ]; then
    set -a
    # shellcheck disable=SC1090
    source "${ENV_FILE}"
    set +a
fi

read_windows_env() {
    local name="$1"
    if command -v powershell.exe >/dev/null 2>&1; then
        powershell.exe -NoProfile -Command "[Environment]::GetEnvironmentVariable('${name}')" | tr -d '\r'
    fi
}

# 配置参数
: "${REMOTE_HOST:?REMOTE_HOST environment variable is required}"
: "${REMOTE_USER:?REMOTE_USER environment variable is required}"
: "${REMOTE_PATH:?REMOTE_PATH environment variable is required}"
: "${REMOTE_REPOS_PATH:?REMOTE_REPOS_PATH environment variable is required}"
: "${REMOTE_GITNEXUS_DATA_PATH:?REMOTE_GITNEXUS_DATA_PATH environment variable is required}"
: "${REMOTE_LBDB_PATH:?REMOTE_LBDB_PATH environment variable is required}"
: "${REGISTRY_HOST:?REGISTRY_HOST environment variable is required}"
: "${REGISTRY_PORT:?REGISTRY_PORT environment variable is required}"
: "${REGISTRY_NAMESPACE:?REGISTRY_NAMESPACE environment variable is required}"
REGISTRY_URL="${REGISTRY_HOST}:${REGISTRY_PORT}/${REGISTRY_NAMESPACE}"
IMAGE_NAME="gitnexus-mcp-proxy"
KEYWORD_SUMMARY_CONTAINER="gitnexus-keyword-summary"
TAR_FILE="gitnexus_noble_deploy.tar.gz"
RAW_TAR_FILE="${TAR_FILE%.gz}"
BUILDX_BUILDER="gitnexus-deploy-builder"
REMOTE_ENV_FILE="$(mktemp)"
cleanup() {
    rm -f "${REMOTE_ENV_FILE}"
}
trap cleanup EXIT
if [ -z "${GITNEXUS_GITEA_TOKEN:-}" ]; then
    GITNEXUS_GITEA_TOKEN="${gitnexus_gitea_token:-${GITEA_TOKEN:-}}"
fi
if [ -z "${GITNEXUS_GITEA_TOKEN:-}" ]; then
    GITNEXUS_GITEA_TOKEN="$(read_windows_env GITNEXUS_GITEA_TOKEN)"
fi
if [ -z "${GITNEXUS_GITEA_TOKEN:-}" ]; then
    GITNEXUS_GITEA_TOKEN="$(read_windows_env gitnexus_gitea_token)"
fi
if [ -z "${GITNEXUS_GITEA_TOKEN:-}" ]; then
    GITNEXUS_GITEA_TOKEN="$(read_windows_env GITEA_TOKEN)"
fi
export GITEA_TOKEN="${GITNEXUS_GITEA_TOKEN}"
: "${GITEA_TOKEN:?GITNEXUS_GITEA_TOKEN or GITEA_TOKEN environment variable is required}"
if [ -z "${GITNEXUS_KEYWORD_SUMMARY_API_KEY:-}" ]; then
    GITNEXUS_KEYWORD_SUMMARY_API_KEY="$(read_windows_env GITNEXUS_KEYWORD_SUMMARY_API_KEY)"
fi
LOCAL_KEYWORD_SUMMARY_URL="http://keyword-summary:8080"
KEYWORD_SUMMARY_EXTERNAL_URL="${GITNEXUS_KEYWORD_SUMMARY_DEPLOY_URL:-}"
if [ -z "${KEYWORD_SUMMARY_EXTERNAL_URL}" ] && [ -n "${GITNEXUS_KEYWORD_SUMMARY_URL:-}" ] && [ "${GITNEXUS_KEYWORD_SUMMARY_URL}" != "${LOCAL_KEYWORD_SUMMARY_URL}" ]; then
    KEYWORD_SUMMARY_EXTERNAL_URL="${GITNEXUS_KEYWORD_SUMMARY_URL}"
fi
: "${KEYWORD_SUMMARY_EXTERNAL_URL:?GITNEXUS_KEYWORD_SUMMARY_DEPLOY_URL or remote GITNEXUS_KEYWORD_SUMMARY_URL environment variable is required}"
GITNEXUS_KEYWORD_SUMMARY_URL="${KEYWORD_SUMMARY_EXTERNAL_URL}"
export GITNEXUS_KEYWORD_SUMMARY_MODEL="${GITNEXUS_KEYWORD_SUMMARY_MODEL:-qwen3.6-35b-carnice}"
export GITNEXUS_KEYWORD_SUMMARY_API_KEY="${GITNEXUS_KEYWORD_SUMMARY_API_KEY:-}"
: "${GITNEXUS_KEYWORD_SUMMARY_API_KEY:?GITNEXUS_KEYWORD_SUMMARY_API_KEY environment variable is required}"
: "${GITNEXUS_EMBEDDING_URL:?GITNEXUS_EMBEDDING_URL environment variable is required}"
: "${GITNEXUS_INDEX_EMBEDDING_URL:?GITNEXUS_INDEX_EMBEDDING_URL environment variable is required}"
: "${GITNEXUS_NEO4J_PASSWORD:?GITNEXUS_NEO4J_PASSWORD environment variable is required}"

write_remote_env() {
    : > "${REMOTE_ENV_FILE}"
    {
        echo "# Generated by remote_deploy.sh. Do not commit this file."
        echo "REMOTE_PATH=${REMOTE_PATH}"
        echo "REMOTE_REPOS_PATH=${REMOTE_REPOS_PATH}"
        echo "REMOTE_GITNEXUS_DATA_PATH=${REMOTE_GITNEXUS_DATA_PATH}"
        echo "REMOTE_LBDB_PATH=${REMOTE_LBDB_PATH}"
        echo "GITEA_TOKEN=${GITEA_TOKEN}"
        echo "GITNEXUS_EMBEDDING_URL=${GITNEXUS_EMBEDDING_URL}"
        echo "GITNEXUS_INDEX_EMBEDDING_URL=${GITNEXUS_INDEX_EMBEDDING_URL}"
        echo "GITNEXUS_EMBEDDING_MODEL=${GITNEXUS_EMBEDDING_MODEL:-qwen3-embedding-4b}"
        echo "GITNEXUS_EMBEDDING_DIMS=${GITNEXUS_EMBEDDING_DIMS:-2560}"
        echo "GITNEXUS_KEYWORD_SUMMARY_URL=${GITNEXUS_KEYWORD_SUMMARY_URL}"
        echo "GITNEXUS_KEYWORD_SUMMARY_MODEL=${GITNEXUS_KEYWORD_SUMMARY_MODEL}"
        echo "GITNEXUS_KEYWORD_SUMMARY_API_KEY=${GITNEXUS_KEYWORD_SUMMARY_API_KEY}"
        echo "GITNEXUS_KEYWORD_SUMMARY_MAX_TOKENS=${GITNEXUS_KEYWORD_SUMMARY_MAX_TOKENS:-512}"
        echo "GITNEXUS_KEYWORD_SUMMARY_ENABLED=true"
        echo "GITNEXUS_NEO4J_USER=${GITNEXUS_NEO4J_USER:-neo4j}"
        echo "GITNEXUS_NEO4J_PASSWORD=${GITNEXUS_NEO4J_PASSWORD}"
        echo "HOST_ZOEKT_PORT=${HOST_ZOEKT_PORT:-6070}"
        echo "HOST_NEO4J_HTTP_PORT=${HOST_NEO4J_HTTP_PORT:-7474}"
        echo "HOST_NEO4J_BOLT_PORT=${HOST_NEO4J_BOLT_PORT:-7687}"
        echo "HOST_KEYWORD_SUMMARY_PORT=${HOST_KEYWORD_SUMMARY_PORT:-955}"
        echo "HOST_GITNEXUS_HTTP_PORT=${HOST_GITNEXUS_HTTP_PORT:-1347}"
        echo "HOST_GITNEXUS_MCP_PORT=${HOST_GITNEXUS_MCP_PORT:-1350}"
    } >> "${REMOTE_ENV_FILE}"
}

# 自动修复 Windows Bash 下的 Docker 路径问题
DOCKER_HELPER_PATH=$(where.exe docker-credential-desktop.exe 2>/dev/null | head -n 1)
if [ -n "$DOCKER_HELPER_PATH" ]; then
    DOCKER_BIN_DIR=$(dirname "$DOCKER_HELPER_PATH" | sed 's/\\/\//g' | sed 's/C:/\/c/' | sed 's/c:/\/c/')
    export PATH="$PATH:$DOCKER_BIN_DIR"
fi

echo "=== 步骤 1: 本地构建镜像 (使用缓存) ==="

export DOCKER_BUILDKIT=1
rm -f "${RAW_TAR_FILE}" "${TAR_FILE}"
if ! docker buildx inspect "${BUILDX_BUILDER}" >/dev/null 2>&1; then
    docker buildx create --name "${BUILDX_BUILDER}" --driver docker-container --use
fi
docker buildx inspect "${BUILDX_BUILDER}" --bootstrap >/dev/null
MSYS_NO_PATHCONV=1 docker buildx build \
    --builder "${BUILDX_BUILDER}" \
    -t "${IMAGE_NAME}:latest" \
    -f mcp_proxy_docker/Dockerfile \
    --build-arg VITE_BACKEND_URL=/ \
    --output "type=docker,dest=${RAW_TAR_FILE}" \
    .

echo ""
echo "=== 步骤 2: 压缩镜像归档 ==="
gzip -f "${RAW_TAR_FILE}"

echo ""
echo "=== 步骤 3: 传输镜像和配置到远端 ==="
write_remote_env
ssh "${REMOTE_USER}@${REMOTE_HOST}" -T << EOF
    set -e
    mkdir -p "${REMOTE_PATH}/models" "${REMOTE_REPOS_PATH}" "${REMOTE_GITNEXUS_DATA_PATH}" "${REMOTE_LBDB_PATH}"
    if [ -f "${REMOTE_PATH}/repos.json" ]; then cp "${REMOTE_PATH}/repos.json" "${REMOTE_PATH}/repos.json.bak"; fi
    if [ -f "${REMOTE_REPOS_PATH}/repos.json" ]; then cp "${REMOTE_REPOS_PATH}/repos.json" "${REMOTE_REPOS_PATH}/repos.json.bak"; fi
    if [ -f "${REMOTE_GITNEXUS_DATA_PATH}/registry.json" ]; then cp "${REMOTE_GITNEXUS_DATA_PATH}/registry.json" "${REMOTE_PATH}/registry.json.bak"; fi

    echo "Neo4j 模式不再备份 LadybugDB 索引 meta.json"
EOF
TRANSFER_FILES=("${TAR_FILE}" "mcp_proxy_docker/auto_verify.py" "mcp_proxy_docker/docker-compose.yml")
if [ -f "repos.json" ]; then
    TRANSFER_FILES+=("repos.json")
else
    echo "WARN: 本地 repos.json 不存在，保留远端现有仓库配置。"
fi
scp "${TRANSFER_FILES[@]}" "${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH}/"
scp "${REMOTE_ENV_FILE}" "${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH}/.env"
ssh "${REMOTE_USER}@${REMOTE_HOST}" "chmod 600 '${REMOTE_PATH}/.env'"

echo ""
echo "=== 步骤 4: 远程部署与启动 ==="
ssh "${REMOTE_USER}@${REMOTE_HOST}" -T << EOF
    set -e
    cd "${REMOTE_PATH}"

    echo "正在加载镜像..."
    gunzip -c "${TAR_FILE}" | docker load

    echo "清理传输文件..."
    rm "${TAR_FILE}"

    echo "停止并清理旧的独立容器 (如有)..."
    docker stop -t 30 "${IMAGE_NAME}" 2>/dev/null || true
    docker rm "${IMAGE_NAME}" 2>/dev/null || true
    docker stop -t 30 "${KEYWORD_SUMMARY_CONTAINER}" 2>/dev/null || true
    docker rm "${KEYWORD_SUMMARY_CONTAINER}" 2>/dev/null || true

    echo "使用远程 keyword summary 服务: ${GITNEXUS_KEYWORD_SUMMARY_URL}"

    echo "启动 GitNexus + Zoekt (docker compose)..."
    docker compose --env-file .env -f docker-compose.yml up -d gitnexus-mcp-proxy

    echo "--- 执行自动验证 ---"
    python3 auto_verify.py

    echo "--- 清理旧 GitNexus 镜像 ---"
    docker images --format '{{.Repository}} {{.Tag}} {{.ID}}' \
      | awk '\$1 == "${REGISTRY_URL}/${IMAGE_NAME}" { print \$1 ":" \$2 } \$1 == "${IMAGE_NAME}" && \$2 != "latest" { print \$1 ":" \$2 }' \
      | xargs -r docker rmi 2>/dev/null || true
    docker image prune -f
EOF

echo ""
echo "=== 步骤 5: 部署完成，查看日志 ==="
ssh "${REMOTE_USER}@${REMOTE_HOST}" "docker logs --tail 20 ${IMAGE_NAME}"

# 本地清理
rm -f "${TAR_FILE}"
